-----PRACTICAL-5-----
-----PART-B-----

--1. Write a SQL query to determine the highest purchase amount made by each salesperson on '2012-08-17'. Return salesperson ID, purchase amount.
select salesman_id,max(purch_amt) from ORDERS where ord_date = '17-AUG-2012' group by salesman_id 

--2. Write a SQL query to find the highest order (purchase) amount by each customer on a particular order date. Filter the result by highest order (purchase) amount above 2000.00. Return customer id, order date and maximum purchase amount.
select customer_id,ord_date,max(purch_amt) from ORDERS group by customer_id,ord_date having max(purch_amt) > 2000

--3. Write a SQL query to find the maximum order (purchase) amount in the range 2000 - 6000 (Begin and end values are included.) by combination of each customer and order date. Return customer id, order date and maximum purchase amount.
select customer_id,ord_date,max(purch_amt) from ORDERS group by customer_id,ord_date having max(purch_amt) >= 2000 and max(purch_amt) <= 6000

--4. Write a SQL query to find the maximum order (purchase) amount based on the combination of each customer and order date. Filter the rows for maximum order (purchase) amount is either 2000, 3000, 5760, 6000. Return customer id, order date and maximum purchase amount.
select customer_id,ord_date,max(purch_amt) from ORDERS group by customer_id,ord_date having max(purch_amt) in (2000, 3000, 5760, 6000)

--5. Write a SQL query to determine the maximum order amount for each customer. The customer ID should be in the range 3002 and 3007(Begin and end values are included.). Return customer id and maximum purchase amount.
select customer_id,max(purch_amt) from ORDERS group by customer_id having customer_id >= 3002 and customer_id <= 3007

--6. Write a SQL query to find the maximum order (purchase) amount for each customer. The customer ID should be in the range 3002 and 3007(Begin and end values are included.). Filter the rows for maximum order (purchase) amount is higher than 1000. Return customer id and maximum purchase amount.
select customer_id,max(purch_amt) from ORDERS group by customer_id having customer_id >= 3002 and customer_id <= 3007 and max(purch_amt) > 1000

--7. Write a SQL query to determine the maximum order (purchase) amount generated by each salesperson. Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.). Return salesperson id and maximum purchase amount.
select salesman_id,max(purch_amt) from ORDERS group by salesman_id having salesman_id >= 5003 and salesman_id <= 5008

--8. Write a SQL query to count all the orders generated on '2012-08-17'. Return number of orders.
select count(ord_no) as [Number of Order] from ORDERS where ord_date = '17-AUG-2012'

--9. Write a SQL query to count the number of salespeople in a city. Return number of salespeople.
select city,COUNT(salesman_id) as [Number of Salespeople in a City] from salesmen group by city

--10. Write a SQL query to count the number of orders based on the combination of each order date and salesperson. Return order date, salesperson id.
select ord_date, salesman_id,count(ord_no) as [Number of Order] from ORDERS group by ord_date,salesman_id