CREATE TABLE PERSON(ID INT,NAME VARCHAR(50),AGE INT,CITY VARCHAR(50),ISACTIVE VARCHAR(50));

INSERT INTO PERSON VALUES(1,'John',30,'New York','true');
INSERT INTO PERSON VALUES(2,'Jane',25,'Los Angeles','false');
INSERT INTO PERSON VALUES(3,'Tom',35,'Chicago','true');
INSERT INTO PERSON VALUES(4,'Lucy',28,'San Francisco','true');
INSERT INTO PERSON VALUES(5,'David',40,'Miami','false');
INSERT INTO PERSON VALUES(6,'Eva',23,'Boston','true');
INSERT INTO PERSON VALUES(7,'Nick',38,'Seattle','false');
INSERT INTO PERSON VALUES(8,'Sophia',27,'New York','true');
INSERT INTO PERSON VALUES(9,'Liam',32,'Los Angeles','false');
INSERT INTO PERSON VALUES(10,'Olivia',29,'San Diego','true');

-- 1 --
SELECT  * FROM PERSON;

-- 2 --
SELECT * FROM PERSON WHERE AGE=30;

-- 3 --
SELECT * FROM PERSON WHERE AGE>25;

-- 4 --
SELECT * FROM PERSON WHERE NAME='John' AND AGE=30;

-- 5 --
SELECT * FROM PERSON WHERE AGE != 25;

-- 6 --
SELECT * FROM PERSON WHERE AGE IN(25,30,35);

-- 7 --
SELECT * FROM PERSON WHERE AGE=30 AND NAME='John';

-- 8 --
SELECT * FROM PERSON WHERE AGE>25 AND CITY='New York';

-- 9 --
SELECT AGE,CITY FROM PERSON WHERE NAME='John';

-- 10 --
SELECT * FROM PERSON 
ORDER BY AGE;

-- 11 --
SELECT * FROM PERSON 
ORDER BY AGE DESC;

-- 12 --
SELECT * FROM PERSON 
ORDER BY NAME,AGE DESC;

-- 13 --
SELECT TOP 5 * FROM PERSON;

-- 14 --
SELECT NAME FROM PERSON WHERE NAME LIKE '[a-d]%' OR NAME LIKE '[t-z]%';

-- 15 --
SELECT CITY,COUNT(ID) FROM PERSON
GROUP BY CITY
ORDER BY CITY;